### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by enessanal**
Added a token with read-only priv.

### CODE REVIEW

**Comment by enessanal** [comment]
hi!

**Comment by optimalres** [comment]
why?

**Comment by enessanal** [comment]
gift token with read-only priv.

**Comment by enessanal** [comment]
200 GET request in 10 days.
But max 10 request per 60 secs.

**Comment by optimalres** [comment]
ok thank you very much!

**Comment by enessanal** [comment]
thanks

**Pull request merged**
